Attribute VB_Name = "gzAddPH7AtrFlds"
Option Compare Text
Option Explicit
Const CLib$ = "QAppMB52."
Const CMod$ = CLib & "gzAddPH7AtrFlds."
Const L4Atr$ = "Srt4,PHNam,PHBrd,PHQGp,PHQly"
Const L3Atr$ = "Srt3,PHNam,PHBrd,PHQGp"
Const L2Atr$ = "Srt2,PHNam,PHBrd"
Const L1Atr$ = "Srt1,PHNam"
Const StmAt1r$ = "Stream"
Const BusAtr$ = "Stream,PHSBus as Srt,PHBus"   ' Srt is renamed from PHLBus->PHSBu
Const SkuAtr$ = "Stream,Srt4,PHL4,PHNam,PHBrd,PHQGp,PHQly,SkuDes"

Const L4Ord$ = "x.Stm,Srt4,PHNam,PHBrd,PHQGp,PHQly"
Const L3Ord$ = "x.Stm,Srt3,PHNam,PHBrd,PHQGp"
Const L2Ord$ = "x.Stm,Srt2,PHNam,PHBrd"
Const L1Ord$ = "x.Stm,Srt1,PHNam"
Const SkuOrd$ = "Stream,Srt4,x.Sku"
Const BusOrd$ = "x.Stm,PHSBus,PHBus"
Const StmOrd$ = "Stream"

'Sub T_Stm(): AddStmAtr FmStm, "#A": Opn_Tbl "#A": End Sub
'Sub T_Bus(): AddBusAtr FmBus, "#A": Opn_Tbl "#A": End Sub
'Sub T_Sku(): AddSkuAtr FmSku, "#A": Opn_Tbl "#A": End Sub
'Sub T_L1(): AddL1Atr FmL1, "#A": Opn_Tbl "#A": End Sub
'Sub T_L2(): AddL2Atr FmL2, "#A": Opn_Tbl "#A": End Sub
'Sub T_L3(): AddL3Atr FmL3, "#A": Opn_Tbl "#A": End Sub
'Sub T_L4(): AddL4Atr FmL4, "#A": Opn_Tbl "#A": End Sub
'Sub: AddL4Atr
    'Inp: #FmTbl
    'Oup: #ToTbl
    'Ref: $PHL4 = PHL4 | Srt4 PHNam PHBrd PHQGp PHQly
    'Ref: PHLStm = Stm | Stream
    ':L4Atr: :List-Of-Fields ! it means fields {Stream Srt4 PHNam PHBrd PHQGp PHQly}
    '@RstFlds: Rest of fields without comma in front
    'Where: #FmTbl = RplL4(FmTblQStr)
    '       #ToTbl = RplL4(ToTblQStr)
'Aim: Create #ToTbl by #FmTbl by adding L4-Atr-Fields from @PHL4
'Example: Following sql will be generated by these
    'Parameters:
        '@Fm="@StkHld?"
        '@ToTbl="#StkHld?"
        '@RstFlds = ",ScCsg,HkdCsg,ScDf,HkdDf,ScDp,HkdDp,'' as F1,ScGit,HkdGit,'' as F2,ScTot,HkdTot"
    'OupSql:
        'SELECT StreamzStm(Stm) As Stream,Srt4,x.PHL4,PHNam,PHBrd,PHQGp,PHQly,...
        ' INTO [@StkHldL4]
        ' FROM [#StkHldL4] x
        ' LEFT JOIN [$PHL4] a on x.PHL4=a.PHL4
        'Order by Stm,Srt4,PHNam,PHBrd,PHQGp,PHQly @@

'Sub: AddL3Atr1
    'Inp: #FmTbl
    'Oup: #ToTbl
    'Ref: $PHL3 = PHL3 | Srt3 PHNam PHBrd PHQGp
    'Ref: PHLStm = Stm | Stream
    ':L3Atr: :List-Of-Fields ! it means fields {Stream Srt3 PHNam PHBrd PHQGp}
    '@RstFlds: Rest of fields without comma in front
    'Where: #FmTbl = RplL3(FmL3TblQStr)
    '       #ToTbl = RplL3(ToL3TblQStr)
'Aim: Create #ToTbl by #FmTbl by adding L3-Atr-Fields from @PHL3
'Example: Following sql will be generated by these Parameters:
    'Parameters
        '@Fm="@StkHld?"
        '@ToTbl="#StkHld?"
        '@RstFlds = "ScCsg,HkdCsg,ScDf,HkdDf,ScDp,HkdDp,'' as F1,ScGit,HkdGit,'' as F2,ScTot,HkdTot"
    'OupSql =
        'SELECT Stream,Srt3,x.PHL3,PHNam,PHBrd,PHQGp..
        ' INTO [@StkHldL3]" & _
        ' FROM [#StkHldL3] x" & _
        ' LEFT JOIN [$PHL3] a on x.PHL3=a.PHL3" & _
        ' Order by Stm,Srt3,PHNam,PHBrd,PHQGp"
Sub AddPH7Atr(FmTblQStr$, ToTblQStr$)
'Inp: $PHL1..4 & $PHSku(See TmpPH)
'Oup: each of the FmTbl-QStr-@FmTblQStr, add attribute fields from $PH{5}
StsQry "PH7Atr"
AddSkuAtr FmTblQStr, ToTblQStr
AddBusAtr FmTblQStr, ToTblQStr
AddStmAtr FmTblQStr, ToTblQStr
AddL4Atr FmTblQStr, ToTblQStr
AddL3Atr FmTblQStr, ToTblQStr
AddL2Atr FmTblQStr, ToTblQStr
AddL1Atr FmTblQStr, ToTblQStr
End Sub

Private Sub AddStmAtr(FmTblQStr$, ToTblQStr$)
'FmTbl should have Stm
Dim FmTbl$: FmTbl = RplStm(FmTblQStr)
Dim ToTbl$: ToTbl = RplStm(ToTblQStr)
Dim Sql$: Sql = "SELECT x.*," & StmAt1r & _
" Into [" & ToTbl & "]" & _
" From ([" & FmTbl & "] x" & _
" LEFT JOIN PHLStm a on x.Stm=a.Stm)" & _
" Order by " & StmOrd
RunCQ Sql
DrpStm ToTbl
End Sub

Private Sub AddSkuAtr(FmTblQStr$, ToTblQStr$)
'@FmTbl should be Sku
Dim FmTbl$: FmTbl = RplSku(FmTblQStr)
Dim ToTbl$: ToTbl = RplSku(ToTblQStr)
Dim Sql$: Sql = "SELECT x.*," & SkuAtr & _
" Into [" & ToTbl & "]" & _
" From ([" & FmTbl & "] x" & _
" LEFT JOIN [$PHSku] a on x.Sku=a.Sku)" & _
" Order by " & SkuOrd
RunCQ Sql
End Sub

Private Sub AddBusAtr(FmTblQStr$, ToTblQStr$)
'@FmTbl should be Stm,BusArea
Dim FmTbl$: FmTbl = RplBus(FmTblQStr)
Dim ToTbl$: ToTbl = RplBus(ToTblQStr)
Dim Sql$: Sql = "SELECT x.*," & BusAtr & _
" Into [" & ToTbl & "]" & _
" From ([" & FmTbl & "] x" & _
" LEFT JOIN [PHLBus] a on x.BusArea=a.BusArea)" & _
" LEFT JOIN [PHLStm] b on x.Stm  =b.Stm" & _
" Order by " & BusOrd
RunCQ Sql
DrpStm ToTbl
End Sub

Private Sub AddL4Atr(FmTblQStr$, ToTblQStr$)
Dim FmTbl$: FmTbl = RplL4(FmTblQStr)
Dim ToTbl$: ToTbl = RplL4(ToTblQStr)
Dim Sql$: Sql = "SELECT Stream,x.*," & L4Atr & _
" Into [" & ToTbl & "]" & _
" From ([" & FmTbl & "] x" & _
" LEFT JOIN [$PHL4] a on x.PHL4=a.PHL4)" & _
" LEft Join [PHLStm] b on b.Stm=x.Stm" & _
" Order by " & L4Ord
RunCQ Sql
DrpStm ToTbl
End Sub

Private Sub AddL3Atr(FmTblQStr$, ToTblQStr$)
Dim FmTbl$: FmTbl = RplL3(FmTblQStr)
Dim ToTbl$: ToTbl = RplL3(ToTblQStr)
Dim Sql$: Sql = "SELECT Stream,x.*," & L3Atr & _
" Into [" & ToTbl & "]" & _
" From ([" & FmTbl & "] x" & _
" LEFT JOIN [$PHL3] a on x.PHL3=a.PHL3)" & _
" LEft Join [PHLStm] b on b.Stm=x.Stm" & _
" Order by " & L3Ord
RunCQ Sql
DrpStm ToTbl
End Sub

Private Sub AddL2Atr(FmTblQStr$, ToTblQStr$)
'FmTbl should have Stm PHL2
Dim FmTbl$: FmTbl = RplL2(FmTblQStr)
Dim ToTbl$: ToTbl = RplL2(ToTblQStr)
Dim Sql$: Sql = "SELECT Stream, x.*," & L2Atr & _
" Into [" & ToTbl & "]" & _
" From ([" & FmTbl & "] x" & _
" LEFT JOIN [$PHL2] a on x.PHL2=a.PHL2)" & _
" LEft Join [PHLStm] b on b.Stm=x.Stm" & _
" Order by " & L2Ord
RunCQ Sql
DrpStm ToTbl
End Sub

Private Sub AddL1Atr(FmTblQStr$, ToTblQStr$)
Dim FmTbl$: FmTbl = RplL1(FmTblQStr)
Dim ToTbl$: ToTbl = RplL1(ToTblQStr)
Dim Sql$: Sql = "SELECT Stream,x.*," & L1Atr & _
" Into [" & ToTbl & "]" & _
" From ([" & FmTbl & "] x" & _
" LEFT JOIN [$PHL1] a on x.PHL1=a.PHL1)" & _
" LEft Join [PHLStm] b on b.Stm=x.Stm" & _
" Order by " & L1Ord
RunCQ Sql
DrpStm ToTbl
End Sub


Private Sub DrpStm(T$)
RunCQ "alter Table [" & T & "] drop column Stm"
End Sub

Private Function FmStm$()
FmStm = "#Fm"
RunCQ "Select Stm into [#Fm] from PHLStm"
End Function
Private Function FmSku$()
FmSku = "#Fm"
RunCQ "Select Sku,SkuDes into [#Fm] from Sku"
End Function
Private Function FmBus$()
FmBus = "#Fm"
RunCQ "Select Stm,BusArea into [#Fm] from PHLBus"
End Function
Private Function FmL4$()
FmL4 = "#Fm"
RunCQ "Select Distinct Stm,Left(ProdHierarchy,10) as PHL4 Into [#Fm] From qSKu_Main group by Stm,LEft(ProdHierarchy,10)"
End Function
Private Function FmL3$()
FmL3 = "#Fm"
RunCQ "Select Distinct Stm,Left(ProdHierarchy,7) as PHL3 Into [#Fm] From qSKu_Main group by Stm,LEft(ProdHierarchy,7)"
End Function
Private Function FmL2$()
FmL2 = "#Fm"
RunCQ "Select Distinct Stm,Left(ProdHierarchy,4) as PHL2 Into [#Fm] From qSKu_Main group by Stm,LEft(ProdHierarchy,4)"
End Function
Private Function FmL1$()
FmL1 = "#Fm"
RunCQ "Select Distinct Stm,Left(ProdHierarchy,2) as PHL1 Into [#Fm] From qSKu_Main group by Stm,LEft(ProdHierarchy,2)"
End Function
